spring.application.name=loginbackend

# Server
server.port=8080

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/authapp
spring.datasource.username=root
spring.datasource.password=Vijay19

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# REMOVE THESE (not needed anymore)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# spring.security.user.name=admin
# spring.security.user.password=admin